# Generated by Django 5.2.4 on 2025-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogeneration",
            name="avatar_id",
            field=models.CharField(default="Kristin_public_3_20240108", max_length=255),
        ),
        migrations.AlterField(
            model_name="videogeneration",
            name="voice_id",
            field=models.CharField(
                default="1bd001e7e50f421d891986aad5158bc8", max_length=255
            ),
        ),
    ]
